/*==============================================================*/
/* CREATE VIEW EQUIPMENT_VIEW                                   */
/*==============================================================*/
DROP VIEW IF EXISTS EQUIPMENT_VIEW;
CREATE VIEW EQUIPMENT_VIEW AS
    SELECT 
        EQUIPMENT.EQUIPMENT_ID AS EQUIPMENT_ID,
        EQUIPMENT.EQUIPMENT_NAME AS EQUIPMENT_NAME,
        EQUIPMENT.DESCRIPTION AS DESCRIPTION,
        EQUIPMENT.CREATION_DATE AS CREATION_DATE,
        EQUIPMENT.PRICE AS PRICE,
        EQUIPMENT.TOTAL_QUANTITY AS TOTAL_QUANTITY,
        EQUIPMENT.AVAILABLE_QUANTITY AS AVAILABLE_QUANTITY,
        EQUIPMENT.IMAGE_LINK AS IMAGE_LINK,
        EQUIPMENT.OTHER_TEXT AS OTHER_TEXT,
        CATEGORY.CATEGORY_ID AS CATEGORY_ID,
        CATEGORY.CATEGORY_NAME AS CATEGORY_NAME,
        RENTER.RENTER_ID AS RENTER_ID,
        RENTER.COMPANY_NAME AS COMPANY_NAME,
        RENTER.FIRST_NAME AS FIRST_NAME,
        RENTER.LAST_NAME AS LAST_NAME,
        RENTER.EMAIL AS EMAIL,
        RENTER.BIRTH_DATE AS BIRTH_DATE,
        RENTER.ADDRESS AS ADDRESS,
        RENTER.ADDITIONNAL_ADDRESS AS ADDITIONNAL_ADDRESS,
        RENTER.POSTAL_CODE AS POSTAL_CODE,
        RENTER.CITY AS CITY,
        RENTER.IMAGE_LINK AS RENTER_IMAGE_LINK
    FROM
        ((EQUIPMENT
        JOIN CATEGORY ON (EQUIPMENT.CATEGORY_ID = CATEGORY.CATEGORY_ID))
        JOIN RENTER ON (EQUIPMENT.RENTER_ID = RENTER.RENTER_ID))
    GROUP BY EQUIPMENT.EQUIPMENT_ID;

/*==============================================================*/
/* CREATE VIEW ORDER_VIEW                                       */
/*==============================================================*/
DROP VIEW IF EXISTS ORDER_VIEW;
CREATE VIEW ORDER_VIEW AS
    SELECT 
        EQUIPMENT_ORDER.ORDER_ID AS ORDER_ID,
        EQUIPMENT_ORDER.CLIENT_ID AS CLIENT_ID,
        EQUIPMENT_ORDER.START_DATE AS START_DATE,
        EQUIPMENT_ORDER.FINISH_DATE AS FINISH_DATE,
        EQUIPMENT_ORDER.RENT_DATE AS RENT_DATE,
        EQUIPMENT_ORDER.QUANTITY_RENTED AS QUANTITY_RENTED,
        
        BILL.BILL_ID AS BILL_ID,
        BILL.DESCRIPTION AS BILL_DESCRIPTION,
        BILL.BILL_DATE AS BILL_DATE,
        BILL.BILL_PRICE AS BILL_PRICE,
        
        CLIENT.FIRST_NAME AS CLIENT_FIRST_NAME,
        CLIENT.LAST_NAME AS CLIENT_LAST_NAME,
        CLIENT.EMAIL AS CLIENT_EMAIL,
        CLIENT.BIRTH_DATE AS CLIENT_BIRTH_DATE,
        CLIENT.ADDRESS AS CLIENT_ADDRESS,
        CLIENT.ADDITIONNAL_ADDRESS AS CLIENT_ADDITIONNAL_ADDRESS,
        CLIENT.POSTAL_CODE AS CLIENT_POSTAL_CODE,
        CLIENT.CITY AS CLIENT_CITY,
        
        EQUIPMENT.EQUIPMENT_ID AS EQUIPMENT_ID,
        EQUIPMENT.EQUIPMENT_NAME AS EQUIPMENT_NAME,
        EQUIPMENT.DESCRIPTION AS EQUIPMENT_DESCRIPTION,
        EQUIPMENT.CREATION_DATE AS EQUIPMENT_CREATION_DATE,
        EQUIPMENT.PRICE AS EQUIPMENT_PRICE,
        EQUIPMENT.TOTAL_QUANTITY AS EQUIPMENT_TOTAL_QUANTITY,
        EQUIPMENT.AVAILABLE_QUANTITY AS EQUIPMENT_AVAILABLE_QUANTITY,
        EQUIPMENT.IMAGE_LINK AS EQUIPMENT_IMAGE_LINK,
        EQUIPMENT.OTHER_TEXT AS EQUIPMENT_OTHER_TEXT,
        
        CATEGORY.CATEGORY_ID AS CATEGORY_ID,
        CATEGORY.CATEGORY_NAME AS CATEGORY_NAME,
        
        RENTER.RENTER_ID AS RENTER_ID,
		RENTER.COMPANY_NAME AS COMPANY_NAME,
        RENTER.FIRST_NAME AS RENTER_FIRST_NAME,
        RENTER.LAST_NAME AS RENTER_LAST_NAME,
        RENTER.EMAIL AS RENTER_EMAIL,
        RENTER.BIRTH_DATE AS RENTER_BIRTH_DATE,
        RENTER.ADDRESS AS RENTER_ADDRESS,
        RENTER.ADDITIONNAL_ADDRESS AS RENTER_ADDITIONNAL_ADDRESS,
        RENTER.POSTAL_CODE AS RENTER_POSTAL_CODE,
        RENTER.CITY AS RENTER_CITY,
        RENTER.IMAGE_LINK AS RENTER_IMAGE_LINK
    FROM
        (((((EQUIPMENT_ORDER
        JOIN CLIENT ON (EQUIPMENT_ORDER.CLIENT_ID = CLIENT.CLIENT_ID))
        JOIN BILL ON (EQUIPMENT_ORDER.BILL_ID = BILL.BILL_ID))
        JOIN EQUIPMENT ON (EQUIPMENT_ORDER.EQUIPMENT_ID = EQUIPMENT.EQUIPMENT_ID))
        JOIN CATEGORY ON (EQUIPMENT.CATEGORY_ID = CATEGORY.CATEGORY_ID))
        JOIN RENTER ON (EQUIPMENT.RENTER_ID = RENTER.RENTER_ID))
    GROUP BY EQUIPMENT_ORDER.ORDER_ID;  
    
