/*==============================================================*/
/* SCRIPT Authors : Nathan JOUBERT & Allan Mendjeli             */
/* This script is for re-create database                        */
/*==============================================================*/

CREATE DATABASE IF NOT EXISTS sport_and_co;
USE sport_and_co;

/*==============================================================*/
/* DROP Foreign Key                                             */
/*==============================================================*/
alter table EQUIPMENT drop foreign key FK_EQUIPMENT_CONCERNS_CATEGORY_;
      
alter table EQUIPMENT drop foreign key FK_USER_CREATE_EQUIPMENT_;
      
alter table EQUIPMENT_ORDER drop foreign key FK_ORDER_CONCERNS_EQUIPMENT_;
      
alter table EQUIPMENT_ORDER drop foreign key FK_ORDER_CONCERNS_CLIENT_;
      
alter table EQUIPMENT_ORDER drop foreign key FK_ORDER_CONCERNS_BILL_;

/*==============================================================*/
/* DROP Tables                                                  */
/*==============================================================*/
drop table if exists EXEMPLE;
  
drop table if exists ADMINISTRATOR;
  
drop table if exists BILL;
    
drop table if exists EQUIPMENT;

drop table if exists CATEGORY;

drop table if exists RENTER;
  
drop table if exists RENTING_CLIENT;

drop table if exists EQUIPMENT_ORDER;


/*==============================================================*/
CREATE TABLE EXEMPLE (
    EXEMPLE_ID INT NOT NULL AUTO_INCREMENT COMMENT '',
    TITLE VARCHAR(100) COMMENT '',
    PRIMARY KEY auto_increment (EXEMPLE_ID)
);

/*==============================================================*/
CREATE TABLE ADMINISTRATOR (
    ADMINISTRATOR_ID INT NOT NULL AUTO_INCREMENT COMMENT '',
    LOGIN VARCHAR(50) COMMENT '' UNIQUE,
    PASSWORD VARCHAR(250) COMMENT '',
    PRIMARY KEY auto_increment (ADMINISTRATOR_ID)
);

/*==============================================================*/
CREATE TABLE EQUIPMENT (
    EQUIPMENT_ID INT NOT NULL AUTO_INCREMENT COMMENT '',
    RENTER_ID INT NOT NULL COMMENT '',
    CATEGORY_ID INT NOT NULL COMMENT '',
    EQUIPMENT_NAME VARCHAR(100) COMMENT '',
    DESCRIPTION VARCHAR(1000) COMMENT '',
    CREATION_DATE VARCHAR(100) COMMENT '',
    PRICE INT NOT NULL COMMENT '',
    TOTAL_QUANTITY INT NOT NULL COMMENT '',
    AVAILABLE_QUANTITY INT NOT NULL COMMENT '',
    IMAGE_LINK VARCHAR(500) COMMENT '',
    OTHER_TEXT VARCHAR(1000) COMMENT '',
    PRIMARY KEY auto_increment (EQUIPMENT_ID)
);

/*==============================================================*/
CREATE TABLE CATEGORY (
    CATEGORY_ID INT NOT NULL AUTO_INCREMENT COMMENT '',
    CATEGORY_NAME VARCHAR(50) COMMENT '',
    PRIMARY KEY auto_increment (CATEGORY_ID)
);

/*==============================================================*/
CREATE TABLE RENTER (
    RENTER_ID INT NOT NULL AUTO_INCREMENT COMMENT '',
    PASSWORD VARCHAR(250) COMMENT '',
    ACCEPTED varchar(1) COMMENT '',
    FIRST_NAME VARCHAR(250) COMMENT '',
    LAST_NAME VARCHAR(250) COMMENT '',
    EMAIL VARCHAR(250) COMMENT '',
    BIRTH_DATE VARCHAR(100) COMMENT '',
    ADDRESS VARCHAR(250) COMMENT '',
    ADDITIONNAL_ADDRESS VARCHAR(250) COMMENT '',
    POSTAL_CODE VARCHAR(100) COMMENT '',
    CITY VARCHAR(250) COMMENT '',
    IMAGE_LINK VARCHAR(500) COMMENT '',
    PRIMARY KEY auto_increment (RENTER_ID)
);

/*==============================================================*/
CREATE TABLE RENTING_CLIENT (
    CLIENT_ID INT NOT NULL AUTO_INCREMENT COMMENT '',
    PASSWORD VARCHAR(250) COMMENT '',
    FIRST_NAME VARCHAR(250) COMMENT '',
    LAST_NAME VARCHAR(250) COMMENT '',
    EMAIL VARCHAR(250) COMMENT '',
    BIRTH_DATE VARCHAR(100) COMMENT '',
    ADDRESS VARCHAR(250) COMMENT '',
    ADDITIONNAL_ADDRESS VARCHAR(250) COMMENT '',
    POSTAL_CODE VARCHAR(100) COMMENT '',
    CITY VARCHAR(250) COMMENT '',
    PRIMARY KEY auto_increment (CLIENT_ID)
);

/*==============================================================*/
CREATE TABLE EQUIPMENT_ORDER (
    ORDER_ID INT NOT NULL AUTO_INCREMENT COMMENT '',
    CLIENT_ID INT NOT NULL COMMENT '',
    EQUIPMENT_ID INT NOT NULL COMMENT '',
    BILL_ID INT NOT NULL COMMENT '',
    START_DATE DATE COMMENT '',
    FINISH_DATE DATE COMMENT '',
    RENT_DATE DATE COMMENT '',
    QUANTITY_RENTED INT NOT NULL COMMENT '',
    PRIMARY KEY auto_increment (ORDER_ID)
);

/*==============================================================*/
CREATE TABLE BILL (
    BILL_ID INT NOT NULL AUTO_INCREMENT COMMENT '',
    DESCRIPTION VARCHAR(50) COMMENT '',
    BILL_DATE VARCHAR(100) COMMENT '',
    BILL_PRICE INT NOT NULL COMMENT '',
    PRIMARY KEY auto_increment (BILL_ID)
);

/*==============================================================*/
/* Create Foreign Key                                           */
/*==============================================================*/
alter table EQUIPMENT add constraint FK_EQUIPMENT_CONCERNS_CATEGORY_ foreign key (CATEGORY_ID)
      references CATEGORY (CATEGORY_ID) on delete restrict on update restrict;
      
alter table EQUIPMENT add constraint FK_USER_CREATE_EQUIPMENT_ foreign key (RENTER_ID)
      references RENTER (RENTER_ID) on delete restrict on update restrict;
      
alter table EQUIPMENT_ORDER add constraint FK_ORDER_CONCERNS_EQUIPMENT_ foreign key (EQUIPMENT_ID)
      references EQUIPMENT (EQUIPMENT_ID) on delete restrict on update restrict;
      
alter table EQUIPMENT_ORDER add constraint FK_ORDER_CONCERNS_CLIENT_ foreign key (CLIENT_ID)
      references RENTING_CLIENT (CLIENT_ID) on delete restrict on update restrict;
      
alter table EQUIPMENT_ORDER add constraint FK_ORDER_CONCERNS_BILL_ foreign key (BILL_ID)
      references BILL (BILL_ID) on delete restrict on update restrict;


/*==============================================================*/
/* CREATE VIEW EQUIPMENT_VIEW                                     */
/*==============================================================*/
DROP VIEW IF EXISTS `EQUIPMENT_VIEW`;
CREATE VIEW EQUIPMENT_VIEW AS
    SELECT 
        EQUIPMENT.EQUIPMENT_ID AS EQUIPMENT_ID,
        EQUIPMENT.EQUIPMENT_NAME AS EQUIPMENT_NAME,
        EQUIPMENT.DESCRIPTION AS DESCRIPTION,
        EQUIPMENT.CREATION_DATE AS CREATION_DATE,
        EQUIPMENT.PRICE AS PRICE,
        EQUIPMENT.TOTAL_QUANTITY AS TOTAL_QUANTITY,
        EQUIPMENT.AVAILABLE_QUANTITY AS AVAILABLE_QUANTITY,
        EQUIPMENT.IMAGE_LINK AS IMAGE_LINK,
        EQUIPMENT.OTHER_TEXT AS OTHER_TEXT,
	
        CATEGORY.CATEGORY_ID AS CATEGORY_ID,
        CATEGORY.CATEGORY_NAME AS CATEGORY_NAME,
        
        RENTER.RENTER_ID AS RENTER_ID,
        RENTER.FIRST_NAME AS FIRST_NAME,
        RENTER.LAST_NAME AS LAST_NAME,
        RENTER.EMAIL AS EMAIL,
        RENTER.BIRTH_DATE AS BIRTH_DATE,
        RENTER.ADDRESS AS ADDRESS,
        RENTER.ADDITIONNAL_ADDRESS AS ADDITIONNAL_ADDRESS,
        RENTER.POSTAL_CODE AS POSTAL_CODE,
        RENTER.CITY AS CITY,
        RENTER.IMAGE_LINK AS RENTER_IMAGE_LINK
    FROM
        ((EQUIPMENT
        JOIN CATEGORY ON (EQUIPMENT.CATEGORY_ID = CATEGORY.CATEGORY_ID))
        JOIN RENTER ON (EQUIPMENT.RENTER_ID = RENTER.RENTER_ID))
    GROUP BY EQUIPMENT.EQUIPMENT_ID;


/*==============================================================*/
/* INSERT : CATEGORY                                            */
/*==============================================================*/
INSERT INTO CATEGORY(CATEGORY_NAME)
VALUES
('Extérieurs'),
('Intérieurs'),
('Hiver'),
('Nautique'),
('Eté'),
('Autre');

/*==============================================================*/
/* INSERT : RENTER                                              */
/*==============================================================*/
INSERT INTO `RENTER` (`PASSWORD`,`ACCEPTED`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("magna","1","Alvin","Chava","in.magna@portaelit.edu","1963-09-06","252-7103 Donec Rd.","sapien. Aenean massa. Integer vitae nibh.","08430-50586","Malang"),("Aliquam","1","Ross","Summer","dui@acrisusMorbi.ca","1986-07-22","Ap #469-5937 Eu St.","metus vitae velit egestas lacinia.","139144","Selva di Cadore"),("Nullam","1","Jeremy","Jarrod","nec.leo@elitfermentumrisus.edu","2006-02-21","2607 Nunc Road","Nam ac nulla. In tincidunt congue turpis.","3691","Haasdonk"),("non,","1","Dana","Warren","a.enim@ametultriciessem.ca","1968-10-15","P.O. Box 752, 5091 Ut Street","pharetra","56184","Valmacca"),("natoque","1","Nicholas","Bethany","ipsum.cursus@Aliquamadipiscinglobortis.org","1995-05-13","394-7312 Vel St.","pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus","29281","Lamorteau"),("nibh","1","Jerry","Dale","Mauris.quis.turpis@rutrum.ca","1969-03-18","P.O. Box 623, 4500 Ac Ave","amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque,","9238","Värnamo"),("massa.","1","Quyn","Diana","Suspendisse.tristique.neque@iaculis.co.uk","1968-08-16","P.O. Box 236, 4025 Volutpat St.","sit amet, risus. Donec","240376","Monteu Roero"),("tincidunt","1","Juliet","Desiree","ornare.In.faucibus@egestasnunc.org","2001-08-18","Ap #756-913 Mauris Av.","ultrices","2989 PB","Henstedt-Ulzburg"),("nibh","1","Alea","Debra","at.velit@inmagna.edu","1958-05-20","P.O. Box 897, 5253 Sit St.","sociis natoque penatibus et magnis dis parturient montes, nascetur","2881","Bloomington"),("placerat,","1","Nolan","Ebony","eros.non@arcuetpede.net","1967-01-22","1686 Ipsum St.","eu tellus eu","393713","Ferlach");
INSERT INTO `RENTER` (`PASSWORD`,`ACCEPTED`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("et","1","Ciara","Dominic","mauris.sit.amet@luctus.ca","1991-03-19","Ap #817-1721 Suspendisse St.","consectetuer","29423","Alexeyevka"),("convallis","1","Ray","Emery","sapien.Cras@liberoMorbi.com","1968-06-16","434-2370 Nunc Avenue","Sed et libero.","LN2 0KW","Vorst"),("et","1","Tiger","Wing","Suspendisse.eleifend@dapibusligula.co.uk","1991-10-16","Ap #484-7096 Nunc Ave","Sed malesuada augue ut lacus. Nulla tincidunt,","10710","Shebekino"),("urna.","1","Gary","Jennifer","eleifend.egestas@Mauris.ca","1974-05-15","Ap #148-2760 Egestas Ave","quis, pede. Praesent eu dui.","3337 MP","Dehri"),("consequat","1","Cameron","Dexter","ac.mattis.velit@aceleifend.edu","1960-08-28","976-4385 Porttitor Road","vel nisl. Quisque fringilla euismod enim. Etiam gravida","71142","Borås"),("nunc","1","Aline","Shoshana","adipiscing@risusQuisquelibero.ca","1959-11-19","Ap #887-5960 Ultrices, Avenue","aliquet libero. Integer in magna. Phasellus dolor","Z4645","Habay"),("Etiam","1","Jordan","Medge","Sed@urnaet.ca","1957-12-09","561-5385 Est Avenue","vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at","234197","Coleville Lake"),("malesuada","1","Vanna","Hadley","et.magnis@a.co.uk","1957-10-10","Ap #156-9483 Lorem Rd.","tempor arcu. Vestibulum ut eros non","96510","Allentown"),("Aliquam","1","Gemma","Claudia","Praesent.eu.nulla@conubia.net","1975-10-26","3222 Pellentesque, Avenue","enim consequat purus. Maecenas libero est, congue a, aliquet vel,","09859","Hearst"),("scelerisque","1","Kenneth","Uta","diam.luctus.lobortis@nulla.org","1987-06-19","3580 Id St.","elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non","17783","Hindupur");
INSERT INTO `RENTER` (`PASSWORD`,`ACCEPTED`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("rhoncus","1","Duncan","Graiden","ipsum.dolor@auctorveliteget.co.uk","1962-08-30","Ap #356-366 Adipiscing. Road","Fusce fermentum fermentum arcu. Vestibulum ante ipsum","212338","Barra do Corda"),("cursus","1","Sylvia","Ifeoma","nec@Nuncullamcorpervelit.org","1992-11-26","2558 Adipiscing, Road","Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae,","20150","Driekapellen"),("ultrices.","1","Clementine","Dante","fringilla@tellusnon.com","1975-07-27","4323 Cras Avenue","mi","84094","Bama"),("Donec","1","Kuame","Phelan","a.mi@luctusfelis.co.uk","1984-06-04","Ap #121-466 Arcu. Street","ligula. Nullam enim. Sed nulla ante, iaculis","59775","Pescopagano"),("eu","1","Hadassah","Winifred","ornare@est.net","1965-03-15","P.O. Box 321, 8494 Sit Rd.","sed turpis nec mauris blandit","63459","Cittanova"),("risus.","1","Naomi","Gwendolyn","eu.arcu@etnetuset.com","1960-06-09","224-1341 Ut Rd.","metus sit amet ante.","8668 RE","Mesa"),("dolor.","1","Felix","Thaddeus","sollicitudin@quam.co.uk","1975-08-30","477-1648 Venenatis St.","tortor. Integer aliquam adipiscing lacus. Ut nec","39447","Carmen"),("lacus.","1","Fallon","Simone","dolor.Nulla.semper@nuncrisus.net","1995-03-23","P.O. Box 527, 2426 Ultrices St.","Proin dolor.","10200","Mornimont"),("luctus.","1","Drew","Yolanda","tortor@magnatellusfaucibus.ca","1964-05-07","Ap #885-8022 Donec Ave","tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed","75465","Sanghar"),("a,","1","Sylvester","Haviva","nec@erat.ca","1985-05-22","P.O. Box 588, 2573 Tempor, St.","Integer id magna et ipsum","876053","Kolmont");
INSERT INTO `RENTER` (`PASSWORD`,`ACCEPTED`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("sed","1","Haviva","Tashya","libero.Morbi@SednequeSed.com","1988-12-02","P.O. Box 579, 8412 Ipsum Road","elementum,","26459-889","Penicuik"),("sed,","1","Adena","Forrest","nec.imperdiet@velquam.co.uk","1958-03-20","Ap #410-6338 Curabitur Avenue","mollis. Duis sit amet diam eu dolor egestas","67677","Zeitz"),("nisl","1","Savannah","Orla","vitae.risus@SedmolestieSed.ca","1972-12-30","P.O. Box 677, 699 Libero. St.","vulputate mauris sagittis","4579","Wrexham"),("luctus","1","Vincent","Henry","nisi@sed.co.uk","1962-10-26","9037 Libero St.","primis in faucibus orci luctus et ultrices posuere cubilia Curae;","117582","Santa Inês"),("iaculis","1","Jena","Oliver","tellus@Fusce.net","1991-12-15","Ap #831-8907 Aliquam Rd.","tempus scelerisque, lorem ipsum","25961","Fuenlabrada"),("non","1","Finn","Cora","egestas@Namtempor.net","2001-11-15","P.O. Box 366, 4704 Magna. St.","lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie.","5006","Velsk"),("magna","1","Montana","Bert","risus@Nunclectus.edu","1961-09-25","4808 Sapien, Ave","mauris. Integer sem elit, pharetra ut, pharetra","04915","Caruaru"),("parturient","1","Roanna","Kuame","sem@elitpharetraut.org","1976-02-03","P.O. Box 665, 6801 Nec St.","sem egestas blandit. Nam nulla magna, malesuada vel, convallis","59743","La Rochelle"),("netus","1","Reuben","Savannah","Duis@estac.co.uk","1963-04-09","P.O. Box 811, 7411 Convallis Road","risus. Nulla eget metus eu erat semper rutrum.","UG5 8GK","Capena"),("rhoncus.","1","Anika","Quintessa","elit.fermentum.risus@musDonecdignissim.edu","1976-10-23","8544 Duis Street","Nulla","74269","Palmerston");
INSERT INTO `RENTER` (`PASSWORD`,`ACCEPTED`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("Ut","1","TaShya","Vanna","Mauris.molestie@enimEtiam.edu","1965-07-05","3959 Sem Road","sed pede. Cum sociis natoque penatibus et magnis","389089","Tilburg"),("fames","1","Anastasia","Honorato","non.lobortis@nonsapienmolestie.edu","1960-08-01","704-5870 Amet, Street","In mi pede, nonummy ut,","24414","Illkirch-Graffenstaden"),("placerat","1","Raven","Nicole","Quisque.imperdiet.erat@Aliquameratvolutpat.org","1986-03-31","5761 Suscipit, Rd.","sit amet metus. Aliquam erat","38369","Dunbar"),("pede","1","Unity","Jermaine","dapibus.quam.quis@sitamet.org","1977-09-23","9803 Adipiscing, Av.","auctor vitae,","ON31 0DP","Dir"),("arcu.","1","Christen","Kyra","magna.Suspendisse.tristique@orcitinciduntadipiscing.ca","1961-07-26","5367 Magnis Ave","Nulla eget metus","01316","Frasnes-lez-Gosselies"),("Ut","1","Hector","Brian","felis.adipiscing.fringilla@Aenean.co.uk","1974-04-28","6048 Quisque Road","sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas","819080","Tumbler Ridge"),("eu,","1","Declan","Demetria","Donec.tincidunt@Morbiquis.ca","1968-08-16","294-2599 Amet, Road","Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo.","11186","Accadia"),("erat","1","Gail","Ori","Nullam.feugiat@disparturientmontes.co.uk","1975-04-05","9973 Adipiscing Rd.","fames ac turpis egestas.","Z7323","Akola"),("ante.","1","Montana","William","Sed@metusVivamuseuismod.org","2003-02-10","Ap #221-3672 Et Rd.","lectus pede, ultrices a,","IK6 5OY","Rhemes-Saint-Georges"),("justo","1","Kiayada","Mari","dolor.Fusce@velit.net","2003-12-27","P.O. Box 163, 5518 Ullamcorper, Rd.","egestas. Aliquam","02673","Belmonte del Sannio");
INSERT INTO `RENTER` (`PASSWORD`,`ACCEPTED`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("eu","1","Lee","Xander","nunc.sed.pede@ac.net","1999-10-27","P.O. Box 175, 217 Ac, Av.","metus. Vivamus euismod urna. Nullam lobortis quam a felis","Z1465","PiŽtrebais"),("sit","1","Lilah","Robin","ac@Integer.edu","1984-03-17","9182 Leo, Street","erat neque","69536","LimerlŽ"),("mollis.","1","Mallory","Caesar","mauris.Suspendisse.aliquet@leoCras.co.uk","1986-07-02","6488 Velit. Av.","congue. In scelerisque scelerisque dui. Suspendisse","99221","La Roche-sur-Yon"),("ultrices.","1","Todd","Isabelle","eget.magna@natoque.com","1975-01-25","5931 Dapibus St.","Donec elementum, lorem","949719","Saltcoats"),("Donec","1","Hasad","Nomlanga","nunc@tristique.co.uk","1958-10-11","Ap #492-2528 Amet St.","non, bibendum sed, est. Nunc laoreet lectus quis massa.","399684","Fontaine-l'Evque"),("enim","1","Alec","Ulla","neque@ornarelectusjusto.co.uk","1981-05-14","430-9755 Posuere Street","neque sed dictum eleifend, nunc risus varius orci,","3834","Sala Baganza"),("eu","1","Odette","Petra","est.mauris.rhoncus@turpis.co.uk","1960-03-24","Ap #170-2716 Aenean Road","molestie tellus. Aenean","OP61 8OV","Oostkamp"),("scelerisque","1","Sonya","Riley","Phasellus.elit.pede@Nullamsuscipit.ca","1957-06-21","P.O. Box 848, 5895 Augue Rd.","ut, molestie in, tempus eu, ligula. Aenean euismod","V7S 1G6","Tunja"),("ornare,","1","Damian","Hillary","Nulla.eget.metus@eteuismodet.net","1958-05-06","3748 Interdum Rd.","convallis, ante lectus","15643","Paradise"),("Curabitur","1","Nichole","Raymond","Sed.eu.nibh@lacus.net","1981-03-09","P.O. Box 632, 8630 Purus. Road","accumsan convallis, ante","96055","Vollezele");
INSERT INTO `RENTER` (`PASSWORD`,`ACCEPTED`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("enim.","1","Pamela","Mariko","at.egestas@Duisrisus.com","2001-11-13","P.O. Box 669, 7505 Nunc Road","congue. In scelerisque","436102","Branchon"),("posuere","1","Bradley","Oscar","felis.adipiscing@dolordapibus.ca","1964-12-03","P.O. Box 482, 4561 Purus Road","Quisque ac libero nec ligula consectetuer rhoncus. Nullam","20617","Tlaquepaque"),("vitae","1","Emi","Keegan","non@acorci.ca","1977-12-11","Ap #551-8551 Tempor Avenue","ornare, elit elit","79197","Juazeiro do Norte"),("eros.","1","Martin","Michelle","sagittis.Nullam.vitae@Ut.org","1988-05-04","P.O. Box 624, 4769 Leo. Road","tristique senectus et","82246","Appleby"),("placerat","1","Kendall","Cairo","ac.sem.ut@dignissimtempor.ca","1968-04-03","644 Auctor Rd.","dui. Cras pellentesque. Sed dictum.","57673","Reggio nell'Emilia"),("mi","1","Josephine","Wade","venenatis@leoelementumsem.co.uk","2004-05-26","4862 Sodales Avenue","vitae, aliquet nec, imperdiet nec,","59984","Gambolò"),("non","1","Hollee","Calvin","turpis.Aliquam.adipiscing@ridiculusmus.org","1988-04-08","101-5570 Est. St.","eget, dictum placerat,","96807","Grumo Appula"),("eros","1","Neil","Ryan","nec.tempus.mauris@Etiamgravidamolestie.org","1990-05-18","P.O. Box 325, 8357 Aenean Av.","tempus scelerisque, lorem ipsum sodales purus, in molestie","9291","Lede"),("Cras","1","Carol","Bruce","Proin.sed.turpis@elementumpurus.net","2002-04-28","194-9910 Donec Rd.","felis orci, adipiscing non, luctus sit amet, faucibus","84850","Teno"),("est.","1","Arsenio","Xavier","viverra@quamelementumat.org","1967-11-09","117-4272 Vitae St.","purus gravida sagittis.","203029","Helmsdale");
INSERT INTO `RENTER` (`PASSWORD`,`ACCEPTED`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("est.","1","Amelia","Paloma","eget@euduiCum.com","1999-10-16","764-7753 Etiam Street","erat. Sed nunc est, mollis non,","753274","Illkirch-Graffenstaden"),("et","1","Belle","Salvador","laoreet.ipsum.Curabitur@elitpede.org","1968-05-02","1978 Inceptos St.","sapien. Nunc pulvinar arcu et pede. Nunc sed orci","569912","Vilvoorde"),("Nunc","1","Miriam","Anthony","pellentesque.Sed@felisNullatempor.com","1996-08-03","983-2646 Lectus. Av.","conubia nostra, per inceptos hymenaeos. Mauris ut","XT8 6WK","Malgesso"),("sagittis","1","Stacy","Alea","nec@eu.com","1988-09-15","P.O. Box 848, 4368 Elit Av.","euismod in, dolor. Fusce feugiat.","Z6524","Sint-Kwintens-Lennik"),("gravida.","1","Alfreda","Garth","mauris.Morbi.non@Proinnonmassa.com","1958-07-01","Ap #916-5338 Tempor St.","ullamcorper eu,","36451","Signeulx"),("dignissim.","1","Willa","Keely","bibendum.Donec.felis@odiosagittissemper.edu","1976-07-11","Ap #325-6023 Quisque Rd.","a,","969522","Roveredo in Piano"),("eget,","1","Hope","Dai","amet.orci.Ut@tempusnon.co.uk","2005-07-03","526-4445 Fusce Road","elit pede, malesuada vel, venenatis vel, faucibus","60573","Berwick"),("eros","1","Zephania","Wilma","sed@facilisisfacilisismagna.edu","1970-02-14","9633 Quis Street","vel, convallis in, cursus et,","24511","Uttarpara-Kotrung"),("porttitor","1","Christian","Daryl","Cras.eget.nisi@egetmagnaSuspendisse.org","1970-11-12","Ap #277-9151 Sem Avenue","varius. Nam porttitor scelerisque neque. Nullam","822988","Chagai"),("Quisque","1","Dylan","Amaya","a@semperauctor.ca","1998-09-19","Ap #937-4102 Erat Street","nulla vulputate dui,","03166","Pamplona");
INSERT INTO `RENTER` (`PASSWORD`,`ACCEPTED`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("eu","1","Meredith","India","ligula@massa.edu","1986-08-14","7139 Duis Av.","ut","47048","Pontevedra"),("sodales","1","Miranda","Benjamin","Nunc@euarcu.edu","1961-01-21","261-3062 Justo Road","id enim.","871182","Lelystad"),("non","1","Julie","Alvin","Etiam.imperdiet@tellusfaucibusleo.co.uk","1968-06-23","1532 Posuere Av.","tempus, lorem","137255","Konin"),("Nam","1","Micah","Martena","magna.a.neque@sapien.org","1964-12-08","P.O. Box 708, 5450 Dui. Road","nibh enim, gravida","840223","Vezirköprü"),("sagittis","1","Leila","Wendy","ipsum.dolor@parturientmontes.com","1974-07-29","Ap #778-9963 Lacus. Street","neque. Sed eget lacus. Mauris non","7052","Huntsville"),("ipsum","1","Farrah","Brett","risus.Nulla@nascetur.edu","1961-05-25","9546 Amet, Avenue","dictum ultricies ligula. Nullam enim.","729652","Ila"),("Cras","1","Lareina","Bree","in@Donecsollicitudin.org","1978-12-29","P.O. Box 242, 6036 Dis St.","ultrices. Duis volutpat","C7G 6K7","Spy"),("lorem,","1","Asher","Lael","magnis.dis.parturient@nislQuisquefringilla.org","1971-11-27","604-8803 Sodales Rd.","velit. Sed malesuada augue","15-205","Montemignaio"),("augue,","1","Dacey","Elijah","eget@purusmauris.ca","1981-12-30","1015 Donec Rd.","litora torquent per","632617","Catacaos"),("augue","1","Cooper","Winifred","orci@sed.ca","2004-01-09","7717 Dignissim Avenue","lacus. Aliquam rutrum lorem","9767 LJ","Schiltigheim");
INSERT INTO `RENTER` (`PASSWORD`,`ACCEPTED`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("lobortis","1","Ila","Iliana","risus.Donec@tristique.co.uk","1965-09-27","3215 Mollis St.","neque non quam. Pellentesque habitant morbi tristique senectus et","541355","Gasp�"),("et,","1","Hadley","Alexander","non.luctus.sit@molestie.org","1976-10-25","Ap #667-1789 Mollis Ave","magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna","7791","Burin"),("pede.","1","Quamar","Len","nulla.Integer@arcuetpede.co.uk","1993-10-03","3011 Mi St.","Vivamus euismod","430942","Dallas"),("auctor","1","Adele","John","quam.quis@facilisis.org","2001-02-26","Ap #441-5723 Suspendisse Street","eu metus. In lorem. Donec","69876","Champorcher"),("felis","1","Byron","Daria","nisl.Nulla@tristiquesenectuset.ca","1967-12-25","704-3628 Mus. St.","risus. Nulla eget","01863","Lanaken"),("posuere,","1","Meghan","Kylee","tempor.diam@sedconsequatauctor.edu","2003-08-31","P.O. Box 951, 8608 Adipiscing Road","Duis sit amet diam eu dolor egestas rhoncus. Proin nisl","GD0M 7KW","Hamilton"),("Suspendisse","1","Melanie","Leonard","velit.in@augue.ca","1984-03-28","Ap #359-7927 A, Ave","ornare lectus justo eu arcu. Morbi","31200","Feldkirchen in Kärnten"),("odio.","1","Talon","Gregory","pede.Cras@lacinia.ca","1985-10-24","Ap #723-8453 Vitae, Avenue","tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla","41611","Bukittinggi"),("ipsum.","1","Eaton","Danielle","risus@sagittis.ca","1986-10-25","Ap #884-8903 Blandit. Rd.","vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante.","Z5642","Pasuruan"),("ac","1","Marshall","Xantha","Ut.tincidunt.orci@etmagnis.edu","1958-02-23","P.O. Box 990, 310 Aliquet Avenue","orci, in consequat enim diam","0831 FZ","Puchuncaví");
INSERT INTO `RENTER` (`PASSWORD`,`ACCEPTED`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("ornare,",0,"Astra","Lance","a@Donecporttitor.org","1975-05-09","Ap #548-7234 Montes, Road","ipsum. Curabitur","48442","Sauris"),("tincidunt",0,"Linus","Bertha","rhoncus.id.mollis@elementumsem.edu","1965-09-17","Ap #758-6429 Egestas St.","mauris","71503","Saint-Pierre"),("in",0,"Burke","Jescie","sem.Nulla@sit.org","1958-10-02","508-7943 Lorem Rd.","sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam","N02 9XK","Sint-Gillis"),("vestibulum",0,"Deborah","Cullen","lacinia.vitae.sodales@mollislectuspede.net","1966-01-07","214-5351 Porttitor Rd.","eget laoreet posuere, enim nisl elementum purus, accumsan","770592","Hereford"),("vitae",0,"Nolan","Quamar","elementum.dui@elementum.net","1962-07-26","Ap #815-2107 Elit, Rd.","lectus. Cum sociis natoque penatibus et magnis dis","46344","Chilliwack"),("feugiat",0,"Elmo","Zoe","rutrum@ornarelectusante.net","1972-07-25","Ap #677-921 Feugiat St.","adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem","317369","Greater Hobart"),("ullamcorper",0,"Brynne","Darryl","semper@dui.ca","1959-09-26","791-8655 Dictum Ave","Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit","Z6437","Kuurne"),("dapibus",0,"Yuli","Tobias","libero.Proin@Fusce.co.uk","1969-01-28","P.O. Box 371, 3923 Posuere Avenue","mauris sagittis placerat.","511640","Muno"),("laoreet",0,"Yuri","Suki","ridiculus@consectetueradipiscing.co.uk","1980-01-10","7588 Mauris, Avenue","non enim.","264618","Pemberton"),("quis",0,"Leonard","Caleb","sodales.nisi.magna@estMauriseu.edu","1985-03-17","867-2659 Rhoncus Rd.","ut odio vel est tempor bibendum.","2788","Cessnock");


/*==============================================================*/
/* INSERT : RENTING CLIENT                                      */
/*==============================================================*/
INSERT INTO `RENTING_CLIENT` (`PASSWORD`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("nec,","Ria","Devin","lectus.pede@pedenecante.net","2017-08-02","173-2233 Malesuada Rd.","luctus.","48883","Ergani"),("tempus","Levi","Phyllis","Etiam.laoreet.libero@semmollis.net","2020-10-24","P.O. Box 199, 2879 At St.","Ut sagittis lobortis mauris.","0616 TI","Burnpur"),("ipsum","Camilla","Iona","morbi@felis.org","2010-05-26","Ap #724-3307 Congue St.","pretium neque. Morbi quis","3251","Ellon"),("libero","Octavius","Gabriel","Pellentesque.ultricies@Pellentesque.com","1989-07-29","8196 Lorem Avenue","Mauris nulla. Integer","17439","Paulatuk"),("adipiscing","Caryn","Brianna","aliquam.adipiscing@ornare.ca","1992-05-21","P.O. Box 913, 8007 Nonummy. Road","turpis non enim. Mauris quis","407971","Alingsås"),("orci","Addison","Shoshana","justo.faucibus@Quisquetincidunt.com","1989-02-19","P.O. Box 233, 363 Ipsum. Rd.","ultrices posuere cubilia Curae;","347975","Kashmore"),("vehicula","Brady","Rosalyn","Curabitur.ut.odio@Donecporttitor.org","1956-02-19","1654 Ante. Avenue","metus","163917","La Pintana"),("quis","Davis","Jillian","in.felis.Nulla@ligulaDonec.edu","1964-04-10","429-5809 Donec Rd.","nibh","852806","Annapolis"),("ac","Deacon","Gloria","Curabitur@liberoduinec.com","2007-09-09","341-4505 Pede St.","mollis. Integer","Z1948","Wolfenbüttel"),("Quisque","Callie","Edward","quam.Pellentesque.habitant@semegetmassa.edu","1994-11-24","2395 Lorem Rd.","tellus justo sit","46334","Amqui");
INSERT INTO `RENTING_CLIENT` (`PASSWORD`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("ultrices","Curran","Ocean","eu.tempor@sedsapienNunc.com","2020-08-08","P.O. Box 780, 7221 Morbi St.","blandit","Z6834","Prato Carnico"),("fringilla.","Alma","Melinda","est@vitae.co.uk","1965-05-16","P.O. Box 814, 1369 Sed Road","Maecenas malesuada","1428 GK","Alloa"),("tempor","Sasha","Ingrid","libero.Integer.in@aliquetvelvulputate.com","1963-11-23","Ap #806-8069 Eros Rd.","adipiscing elit. Etiam","402016","Codognè"),("lorem,","Eagan","Hall","Morbi@ametmassa.com","1991-12-31","471-3828 Aliquam Avenue","Donec","B7M 9R3","Termeno sulla strada del vino/Tramin an der Weinstrasse"),("sit","Price","Nell","massa.Integer.vitae@Donecest.ca","2000-04-26","Ap #582-5408 Sollicitudin St.","ullamcorper","23-361","Shrewsbury"),("euismod","Kuame","Doris","Sed.eget.lacus@etrisusQuisque.co.uk","1966-02-04","428-2685 Integer Rd.","Duis dignissim tempor arcu.","Z6475","Oberwart"),("at,","Carter","Idona","nulla.Integer.urna@libero.com","1955-05-23","Ap #982-1633 Semper St.","sed, sapien. Nunc pulvinar arcu","245335","Leticia"),("Maecenas","Sasha","Curran","Pellentesque@est.ca","2016-01-15","Ap #255-6612 Vehicula Av.","auctor","6057","Rosenheim"),("dolor.","Samson","Mufutau","non.ante@nuncInat.edu","1957-04-30","Ap #476-5885 Vehicula Street","sem mollis dui, in","87490","Cranbrook"),("scelerisque","Rebecca","Aquila","libero.Donec.consectetuer@suscipit.com","1955-09-30","7207 Sagittis Rd.","a, dui.","7612","Funtua");
INSERT INTO `RENTING_CLIENT` (`PASSWORD`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("erat,","Clarke","Lydia","posuere@amet.net","1965-01-05","6160 Nec, Av.","luctus aliquet odio.","50212","Chełm"),("Donec","Pascale","Ria","amet.risus@consectetuermauris.edu","1960-08-04","P.O. Box 280, 6488 Semper Ave","felis.","31513","Ziarat"),("elit,","Carol","Ima","neque@molestie.net","1987-05-25","1167 Vestibulum Road","at, velit. Pellentesque","Z4901","Riesa"),("et,","Ashely","Ann","purus.gravida@cursus.edu","2019-05-23","P.O. Box 186, 3183 Lorem Ave","massa. Mauris vestibulum, neque sed","776460","Sluis"),("sed,","Troy","Nicole","Proin.mi.Aliquam@leoCras.co.uk","1986-11-15","602-6468 Enim, Street","ipsum primis in faucibus orci","02583","Lago Verde"),("libero","Joshua","Christine","varius@aliquamenim.ca","1998-02-07","P.O. Box 258, 8321 Curae; St.","vitae sodales nisi magna","51710","Stevoort"),("ac","Lee","Xenos","sit@eteros.ca","1958-10-19","P.O. Box 538, 2797 Nullam Rd.","sit amet,","52196","Saint-Denis"),("nonummy","Anthony","Moana","adipiscing.elit@necmetus.ca","2002-04-24","P.O. Box 910, 3054 Dictum Rd.","a, malesuada id, erat. Etiam","1297","Göteborg"),("lacus","Colby","Jakeem","metus.Vivamus@metus.edu","1976-04-03","578-8251 Amet Av.","aliquam eros turpis non","179964","Renfrew"),("metus.","Raymond","Mallory","enim@nec.co.uk","2009-03-05","P.O. Box 482, 845 Ultricies St.","eu tellus. Phasellus","8958","Santa Fiora");
INSERT INTO `RENTING_CLIENT` (`PASSWORD`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("sit","Erasmus","Katelyn","sem.Pellentesque@vulputateullamcorper.co.uk","2018-02-27","934 Aptent St.","porttitor scelerisque neque. Nullam nisl.","59754","Laval"),("Duis","Amal","Lawrence","Etiam@eusem.ca","1977-08-06","P.O. Box 607, 6682 Mauris St.","scelerisque scelerisque","822681","Isola del Gran Sasso d'Italia"),("Donec","Robin","Veda","Duis.a.mi@diam.org","2013-12-14","Ap #883-8999 Facilisis Road","ut mi. Duis risus","AA3 5YC","Senftenberg"),("lectus","Mark","Inga","augue@metusvitae.co.uk","1970-08-30","322-1898 Dapibus Road","Integer aliquam adipiscing lacus. Ut","6883","Medea"),("consequat,","Cally","Marvin","lobortis.Class.aptent@sempercursus.ca","1979-07-03","727-3389 Semper. Road","ante blandit","417298","San Francisco"),("a,","Latifah","Price","sem.elit@duilectus.org","2018-08-19","Ap #286-969 Mollis St.","Aenean eget metus.","Z7414","Mulchén"),("nibh.","Shana","Tarik","tellus.non@luctusipsumleo.edu","2003-09-15","3303 Sed Av.","cursus et,","663351","Dhule"),("sollicitudin","Iliana","Benedict","metus.vitae.velit@lectusquis.org","1960-02-24","P.O. Box 784, 5295 Egestas Ave","Fusce mi","49810","Kalisz"),("blandit.","Ifeoma","Keefe","et.tristique@etrutrum.net","1962-07-27","P.O. Box 599, 7152 Dis St.","quis urna.","1945","Hyderabad"),("sem","Stone","Gavin","vulputate@nislsemconsequat.net","2000-11-05","P.O. Box 425, 3641 Phasellus Rd.","quis","341076","Villa del Rosario");
INSERT INTO `RENTING_CLIENT` (`PASSWORD`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("in","Isaiah","Lael","eu.metus.In@augue.co.uk","1957-07-18","Ap #777-6416 Nisi. Rd.","Donec est. Nunc","10314","Krasnoznamensk"),("odio","Cain","Cadman","Donec@eleifendegestasSed.edu","2017-05-09","P.O. Box 441, 7331 Luctus Rd.","Donec sollicitudin adipiscing","23645","Albury"),("auctor","Abraham","Leah","mattis.Integer@lectusjustoeu.co.uk","1971-12-11","Ap #313-7235 Sodales. Avenue","congue.","40881","Antey-Saint-Andrè"),("magna","Levi","Leonard","Duis.ac@ornare.ca","2014-05-09","Ap #244-8770 Adipiscing Rd.","et, euismod et,","15616","Juárez"),("Fusce","Brianna","Ivor","Nullam.vitae@adipiscingelit.net","1976-03-06","Ap #771-4376 Ridiculus Ave","Vivamus nibh dolor, nonummy","435242","Hisar"),("tortor","Cade","Oliver","cursus@duinectempus.com","1962-08-25","Ap #842-2167 Nascetur Av.","ipsum. Suspendisse sagittis. Nullam","77-275","Koersel"),("rutrum","Chancellor","Kibo","parturient@quamelementum.com","2012-04-13","114 Dignissim Rd.","bibendum ullamcorper. Duis","75378","Los Patios"),("nec,","Yeo","Rhonda","sodales.Mauris.blandit@eleifendegestas.com","2022-02-27","675 Fringilla. Avenue","mi lacinia mattis. Integer eu","4928 KD","Appelterre-Eichem"),("non,","David","Tyrone","elit.erat@lectus.ca","1977-07-09","P.O. Box 249, 1102 At Rd.","Vivamus euismod urna.","8716","Rajapalaiyam"),("Mauris","Ariel","Adam","vel.faucibus@Donec.net","2018-02-03","3704 Sed Road","metus. In nec orci.","Y4Y 8H2","Musson");
INSERT INTO `RENTING_CLIENT` (`PASSWORD`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("Nullam","Duncan","Shad","risus.Donec@euismodenimEtiam.ca","2006-03-07","P.O. Box 153, 8189 Sagittis Ave","sed, hendrerit a, arcu. Sed","51200","Nimy"),("habitant","Brock","Wallace","ante.blandit@sedsapienNunc.ca","2020-12-16","P.O. Box 141, 3587 Ligula. Rd.","aliquet lobortis,","5021","Junagadh"),("pharetra.","Madeson","Nayda","sodales.elit.erat@sagittis.net","1968-06-07","Ap #538-4863 Vel Road","porttitor vulputate, posuere","16235-44616","Pramaggiore"),("sit","Keith","Jessamine","mus.Proin.vel@etrutrum.ca","1983-03-28","Ap #538-9942 Lorem. Av.","odio sagittis","82-929","Wemmel"),("et","Kaye","Kamal","justo.eu@tellusjustosit.com","2001-11-17","P.O. Box 690, 1928 Metus. Rd.","risus. Nulla eget metus","5509","Qambar Shahdadkot"),("Nunc","Tyrone","Bert","orci@Nulladignissim.ca","1997-10-15","Ap #458-779 Est, Rd.","leo,","4874","Zaanstad"),("dapibus","Alfonso","Plato","parturient.montes.nascetur@metusvitae.co.uk","2004-04-26","P.O. Box 204, 8104 Phasellus Ave","placerat. Cras dictum ultricies ligula.","11701","Hapur"),("Nam","Savannah","Cassandra","Phasellus.vitae.mauris@etarcuimperdiet.ca","1991-04-29","5072 Lorem, St.","nulla.","64870-339","Kawawachikamach"),("Fusce","Odessa","Ian","Suspendisse.tristique@maurisut.net","1979-05-21","1055 Nibh St.","neque. Nullam nisl.","5295 CD","Gorinchem"),("ac,","Claudia","Omar","eu.arcu@fermentumrisus.net","1989-09-18","778-7707 Diam Road","semper tellus","959794","Castello di Godego");
INSERT INTO `RENTING_CLIENT` (`PASSWORD`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("aliquam","Harper","Diana","egestas.lacinia.Sed@ipsumprimis.ca","2017-02-01","550-1723 Elementum, Avenue","erat. Sed","777607","Serrata"),("odio.","Liberty","Serena","egestas@eu.ca","1975-09-20","P.O. Box 183, 9738 Ultrices Av.","interdum libero","88320","Ashbourne"),("ridiculus","Jaime","Zeph","litora.torquent.per@dolorsitamet.net","1989-08-26","227-2957 Mauris Street","sem egestas","641882","Cartago"),("ultricies","Elmo","Dane","augue.id@congueInscelerisque.co.uk","2007-01-01","393-9743 Imperdiet Av.","nibh. Quisque nonummy","MQ39 4DI","Nuraminis"),("accumsan","Jeanette","Hayley","eu.augue@vitaesodales.com","2010-11-10","Ap #846-4641 Proin Ave","nec metus facilisis","9865","Bassiano"),("sem","Briar","Vance","sit@adipiscing.edu","1967-07-01","P.O. Box 978, 3227 Aliquet Road","Donec","57654","Moffat"),("vel,","Sebastian","Hayfa","ullamcorper.magna@aliquamenimnec.co.uk","1955-10-19","349-8466 Nulla St.","mi tempor lorem, eget mollis","383290","Talara"),("Sed","Risa","Wayne","egestas.ligula@ipsum.net","1974-02-04","Ap #227-6132 Tempor St.","non,","136582","Taunton"),("Maecenas","Benjamin","Walter","eleifend.vitae@odio.edu","2010-10-27","P.O. Box 559, 7467 Dictum. St.","tellus justo","8184","Tay"),("scelerisque","Isabella","Owen","nulla.ante.iaculis@milaciniamattis.co.uk","1981-09-07","4690 Pulvinar St.","tellus","89071","Lakki Marwat");
INSERT INTO `RENTING_CLIENT` (`PASSWORD`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("dolor","Alvin","Kermit","In@Sedeueros.ca","1963-08-20","538-8955 Auctor Av.","parturient","3427","Ulsan"),("Cras","Chastity","Cathleen","feugiat@arcuVestibulumante.net","1981-03-20","4421 Vitae, Rd.","ipsum nunc id enim. Curabitur","694821","Pittsburgh"),("egestas","Helen","Olga","eu@necligula.com","1960-07-26","812-6283 Dis Rd.","posuere","SB60 4RY","Columbus"),("magnis","Karina","Jaden","sociis@nisi.org","2021-08-27","P.O. Box 653, 4343 Nec St.","non justo. Proin","7537","Sint-Denijs-Westrem"),("ultrices","Dawn","Jaquelyn","faucibus@nisl.ca","2003-01-11","Ap #980-191 Arcu. Ave","Donec est mauris, rhoncus id,","5289","Parchim	City"),("sed,","Brendan","Kelsie","libero.mauris@quisarcu.co.uk","2018-02-06","Ap #164-825 Vel, St.","sed, sapien. Nunc pulvinar arcu","Z3987","Ogbomosho"),("Integer","Frances","Zoe","sit@pedeacurna.com","1983-08-11","511-537 Interdum. Avenue","lorem, vehicula et, rutrum","26414","Slijpe"),("ipsum","Nelle","Mechelle","scelerisque.dui.Suspendisse@Aliquam.edu","1971-05-11","Ap #341-9815 Lacus. Avenue","nulla ante,","55068","Springdale"),("adipiscing","Shay","Echo","arcu.Morbi.sit@fringillapurus.net","2001-12-07","P.O. Box 363, 8748 A Ave","feugiat non, lobortis quis,","08279-386","Sint-Gillis"),("Curabitur","Jeanette","Bert","Etiam.vestibulum@imperdiet.net","2017-09-13","P.O. Box 565, 9517 Quis Road","feugiat","JU01 7XW","West Ham");
INSERT INTO `RENTING_CLIENT` (`PASSWORD`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("mattis","Cooper","Tiger","elit.erat@Integer.co.uk","1982-09-21","Ap #169-8112 Dolor. Av.","mattis. Cras eget","3791 EB","Markham"),("ornare,","Moses","Sasha","Integer.mollis.Integer@tortorat.com","1979-11-04","Ap #651-8352 Non Rd.","Suspendisse aliquet molestie tellus.","C2K 2RJ","Wood Buffalo"),("Cras","Eliana","Glenna","nulla.Integer@commodotinciduntnibh.co.uk","1985-05-10","P.O. Box 267, 4319 Duis Av.","amet,","P56 8IS","Namur"),("tempor","Brennan","Chester","blandit.at.nisi@metusurnaconvallis.ca","2009-06-13","P.O. Box 327, 3955 Duis Avenue","sagittis","C6Y 8P8","San Floriano del Collio"),("augue","Maggy","Luke","consectetuer@neque.ca","2017-11-10","P.O. Box 379, 1464 Cum St.","Nunc","4332","Vichte"),("odio.","Nigel","Kirestin","suscipit.est@necligulaconsectetuer.ca","1960-09-02","9711 Venenatis Rd.","Quisque fringilla euismod enim.","25878","Anglet"),("diam.","Lyle","Shana","Sed.dictum.Proin@tellusPhasellus.com","1977-10-05","Ap #211-1916 Nunc Ave","massa non ante bibendum ullamcorper.","9727","Sint-Andries"),("pede,","Kimberley","Nash","urna.Nunc@nuncsed.net","1990-08-08","9314 Mauris Rd.","Curae; Phasellus ornare.","11000","Champion"),("Aliquam","Michelle","Rhonda","tempor.lorem@felis.net","1984-04-02","Ap #657-2374 Aliquam Ave","est arcu ac","74269","Waardamme"),("id","Marah","Samantha","Duis@vel.ca","1957-06-06","Ap #409-6381 Ante. Rd.","elit erat vitae risus. Duis","K9E 0N4","Jerzu");
INSERT INTO `RENTING_CLIENT` (`PASSWORD`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`BIRTH_DATE`,`ADDRESS`,`ADDITIONNAL_ADDRESS`,`POSTAL_CODE`,`CITY`) VALUES ("Sed","Aubrey","Nigel","Mauris.non@facilisiSedneque.org","1978-01-01","Ap #519-9138 A St.","pede.","44593-93900","Wimmertingen"),("amet","Amery","Anthony","sit@pede.edu","2006-09-27","242-1129 Tempor Avenue","mollis lectus pede et","265008","Kaiserslauter"),("ac","Ali","Leonard","dignissim.pharetra@Suspendisse.org","1968-06-23","6799 Amet, Av.","diam.","3262","Ghaziabad"),("dis","Joan","Elaine","dolor.dapibus@egestasAliquam.net","1974-07-18","P.O. Box 130, 7252 Tellus. St.","Nulla tempor augue ac ipsum.","75320","Relegem"),("Fusce","Garth","Chester","Sed.eu@rutrum.org","1965-11-13","529-4078 Aliquam Road","dui. Cum sociis natoque","17063","Turgutlu"),("Integer","Kasper","Serina","commodo@ipsumacmi.com","1994-12-13","P.O. Box 881, 6045 Nunc Ave","dis parturient montes, nascetur ridiculus","3815","Contagem"),("enim.","Gloria","Barbara","dictum@lacusNullatincidunt.ca","1997-11-15","Ap #650-8451 Lorem St.","felis. Donec tempor,","91555","Gerpinnes"),("urna.","Craig","Ulla","eget@nonvestibulum.com","2017-08-10","Ap #306-9970 Feugiat Av.","quis, pede. Suspendisse dui. Fusce","10144-63591","Kemerovo"),("eu","Drake","Macey","Pellentesque@consequatauctornunc.com","2014-04-18","6662 Fermentum Street","Fusce diam","01855","Thorembais-Saint-Trond"),("nec","Jackson","Jena","Nunc@elitpellentesquea.com","2013-09-26","429 Aliquam St.","Phasellus","28756-80054","Maple Creek");

/*==============================================================*/
/* INSERT : EQUIPMENT                                           */
/*==============================================================*/
INSERT INTO `EQUIPMENT` (`RENTER_ID`,`CATEGORY_ID`,`EQUIPMENT_NAME`,`DESCRIPTION`,`CREATION_DATE`,`PRICE`,`TOTAL_QUANTITY`,`AVAILABLE_QUANTITY`,`OTHER_TEXT`) VALUES (68,1,"Vélo","nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem","2021-04-18",184,6,4,"eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean"),(5,2,"Combinaison de plongée","Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at","2020-11-11",47,10,3,"ut cursus luctus, ipsum leo elementum sem,"),(88,2,"Fillet de volley","vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante","2020-08-01",22,8,1,"pharetra ut, pharetra sed, hendrerit a,"),(36,5,"Chaussures à crampons","scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed","2020-07-23",141,10,2,"quam vel sapien imperdiet"),(26,1,"Table de ping-png","quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci","2020-12-24",117,4,2,"urna. Nullam lobortis quam a"),(71,1,"Bateau à moteur","magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem","2020-12-17",190,4,3,"adipiscing, enim mi tempor lorem, eget mollis"),(98,4,"Ballons de foot","dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim nisl elementum purus, accumsan interdum libero","2020-07-04",68,8,2,"nec tellus. Nunc lectus pede,"),(2,4,"Ski","erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis","2020-05-22",68,7,1,"torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam"),(64,3,"Combinaison de ski","ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis","2020-12-22",72,10,1,"elit"),(16,3,"Ski","Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus.","2020-09-16",196,10,4,"Praesent eu dui. Cum sociis natoque penatibus");
INSERT INTO `EQUIPMENT` (`RENTER_ID`,`CATEGORY_ID`,`EQUIPMENT_NAME`,`DESCRIPTION`,`CREATION_DATE`,`PRICE`,`TOTAL_QUANTITY`,`AVAILABLE_QUANTITY`,`OTHER_TEXT`) VALUES (41,4,"Ballon de basket","odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis.","2020-12-24",146,6,4,"lectus. Nullam suscipit, est ac facilisis facilisis, magna"),(65,2,"Balle de tennis","tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy","2021-03-12",131,8,1,"eu tempor erat neque non quam. Pellentesque"),(3,3,"Corde d'escalade","nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim.","2020-09-09",133,7,2,"et magnis dis parturient montes,"),(30,4,"Raquette de tennis","suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit","2020-11-27",63,10,3,"pellentesque eget, dictum placerat, augue. Sed"),(61,4,"Bateau à voile","convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id","2021-02-02",107,9,3,"justo eu arcu. Morbi sit amet massa. Quisque porttitor eros"),(37,4,"Ballons de foot","laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi","2021-02-07",33,8,4,"elit fermentum risus, at"),(33,3,"Ballons de foot","eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor","2021-03-03",15,10,3,"metus urna convallis erat,"),(90,5,"Ballon de volley","eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus","2021-01-29",54,7,1,"semper auctor. Mauris"),(95,5,"Combinaison de plongée","Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam","2020-10-06",54,4,3,"in, tempus eu, ligula. Aenean euismod"),(65,3,"Balle de tennis","consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque","2020-05-06",18,4,4,"Vivamus molestie dapibus");
INSERT INTO `EQUIPMENT` (`RENTER_ID`,`CATEGORY_ID`,`EQUIPMENT_NAME`,`DESCRIPTION`,`CREATION_DATE`,`PRICE`,`TOTAL_QUANTITY`,`AVAILABLE_QUANTITY`,`OTHER_TEXT`) VALUES (8,3,"Ballon de volley","a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis","2020-10-01",74,6,4,"a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus"),(46,3,"Corde d'escalade","nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam","2021-04-13",24,6,4,"convallis convallis"),(10,3,"Raquette de ping-pong","Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc.","2020-11-11",183,10,3,"consectetuer adipiscing elit. Curabitur sed tortor. Integer"),(48,5,"Ballon de basket","adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor,","2020-11-07",61,10,3,"nunc id"),(4,1,"Barque","nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec","2020-09-07",111,6,1,"lacus. Nulla tincidunt, neque vitae semper egestas, urna justo"),(57,3,"Surf","in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui.","2020-07-09",107,6,4,"eu nibh"),(61,4,"Table de ping-png","pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu","2020-06-19",50,9,2,"ipsum non arcu. Vivamus sit amet risus. Donec"),(32,3,"Ski","facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna","2020-07-30",127,10,1,"scelerisque sed,"),(65,2,"Raquette de ping-pong","imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat.","2020-06-18",136,9,4,"dictum eu,"),(53,3,"Raquette de tennis","mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et","2020-08-14",92,7,3,"vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim.");
INSERT INTO `EQUIPMENT` (`RENTER_ID`,`CATEGORY_ID`,`EQUIPMENT_NAME`,`DESCRIPTION`,`CREATION_DATE`,`PRICE`,`TOTAL_QUANTITY`,`AVAILABLE_QUANTITY`,`OTHER_TEXT`) VALUES (42,2,"Raquette de ping-pong","hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna.","2021-02-08",191,6,2,"id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut"),(42,2,"Ballon de volley","a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet,","2021-03-10",187,9,4,"aliquam eros turpis non enim. Mauris quis turpis vitae purus"),(74,1,"Ballon de basket","Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi","2020-11-10",71,5,2,"turpis non enim. Mauris quis turpis vitae purus gravida"),(71,3,"Combinaison de ski","nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor,","2020-12-24",167,6,3,"mauris eu elit. Nulla facilisi. Sed neque. Sed"),(84,3,"Bateau à moteur","Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis","2020-12-13",94,8,1,"et magnis dis"),(91,1,"Combinaison de ski","sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi","2020-08-25",47,8,2,"quam a felis ullamcorper viverra. Maecenas iaculis aliquet"),(76,3,"Barque","ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus","2020-12-19",71,8,3,"Phasellus libero mauris, aliquam eu, accumsan"),(55,2,"Panier de basket","nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum","2020-08-22",169,8,4,"amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque,"),(98,4,"Balle de tennis","rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at,","2020-08-21",95,9,3,"vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque"),(65,4,"Vélo","Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam","2021-01-05",16,9,1,"in, hendrerit consectetuer, cursus et, magna. Praesent");
INSERT INTO `EQUIPMENT` (`RENTER_ID`,`CATEGORY_ID`,`EQUIPMENT_NAME`,`DESCRIPTION`,`CREATION_DATE`,`PRICE`,`TOTAL_QUANTITY`,`AVAILABLE_QUANTITY`,`OTHER_TEXT`) VALUES (87,2,"Fillet de volley","odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus.","2020-06-08",24,8,1,"a felis ullamcorper viverra. Maecenas"),(30,1,"Balle de tennis","malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a","2021-05-02",142,8,4,"tincidunt"),(8,4,"Vélo","iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque","2021-04-22",193,5,3,"ut, pharetra sed, hendrerit a, arcu. Sed"),(46,3,"Bateau à voile","vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy","2020-12-06",138,8,4,"ac turpis egestas. Aliquam fringilla cursus purus. Nullam"),(89,5,"Vélo","turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim","2020-06-28",53,4,1,"ante ipsum primis in faucibus"),(29,1,"Ballon de basket","cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit,","2021-05-02",120,6,4,"at, libero. Morbi accumsan laoreet"),(79,3,"Ballons de foot","est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut","2020-05-24",59,7,3,"ligula. Nullam feugiat placerat velit. Quisque"),(16,3,"Ferrari","Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas,","2020-07-08",106,6,2,"egestas. Fusce aliquet magna a neque. Nullam ut nisi"),(51,3,"Barque","lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae","2020-06-19",27,5,4,"at auctor ullamcorper, nisl arcu iaculis"),(26,2,"Fillet de volley","luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et,","2020-12-09",199,5,4,"a, scelerisque sed, sapien. Nunc pulvinar arcu");
INSERT INTO `EQUIPMENT` (`RENTER_ID`,`CATEGORY_ID`,`EQUIPMENT_NAME`,`DESCRIPTION`,`CREATION_DATE`,`PRICE`,`TOTAL_QUANTITY`,`AVAILABLE_QUANTITY`,`OTHER_TEXT`) VALUES (88,1,"Corde à sauter","dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu.","2020-05-26",200,6,1,"risus. In mi pede,"),(81,2,"Combinaison de ski","mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi","2020-08-10",48,7,1,"justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor"),(96,2,"Bateau à voile","dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at,","2020-12-15",159,7,2,"nostra,"),(50,2,"Ballons de foot","nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque,","2020-11-21",49,7,3,"eu enim. Etiam imperdiet dictum magna. Ut tincidunt"),(73,5,"Vélo","aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In","2020-11-01",173,4,2,"sem magna"),(2,2,"Ballons de foot","risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit","2020-12-04",121,7,1,"quam, elementum at, egestas a,"),(3,2,"Barque","mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies","2021-02-24",195,4,4,"Vivamus"),(62,4,"Ballon de volley","orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl","2021-03-04",22,9,1,"luctus et ultrices posuere cubilia Curae; Donec"),(88,1,"Ballons de foot","eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna.","2020-12-19",67,10,3,"Quisque tincidunt"),(30,1,"Ballons de foot","est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus","2020-10-19",117,10,1,"consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing");
INSERT INTO `EQUIPMENT` (`RENTER_ID`,`CATEGORY_ID`,`EQUIPMENT_NAME`,`DESCRIPTION`,`CREATION_DATE`,`PRICE`,`TOTAL_QUANTITY`,`AVAILABLE_QUANTITY`,`OTHER_TEXT`) VALUES (21,5,"Vélo","id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum","2021-01-23",102,10,2,"eget nisi dictum augue malesuada malesuada. Integer id"),(7,2,"Raquette de tennis","posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo.","2020-12-04",56,6,4,"Pellentesque habitant morbi tristique senectus et netus et malesuada"),(18,2,"Ballons de foot","egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras","2020-09-02",172,7,2,"ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet,"),(48,1,"Bateau à voile","Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla.","2021-04-18",170,6,2,"in faucibus orci luctus et ultrices posuere cubilia"),(53,4,"Ferrari","posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis","2021-01-25",122,6,4,"nisi nibh lacinia"),(85,4,"Ballons de foot","varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus.","2021-01-29",32,7,3,"eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin"),(60,5,"Ferrari","Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor","2020-08-06",159,9,2,"euismod est"),(25,5,"Corde d'escalade","magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus","2020-08-01",76,7,2,"dictum eleifend, nunc risus varius"),(66,4,"Ballon de basket","sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin","2020-06-17",108,9,1,"ornare, lectus ante dictum mi,"),(35,2,"Ferrari","gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla,","2020-12-27",199,9,3,"et");
INSERT INTO `EQUIPMENT` (`RENTER_ID`,`CATEGORY_ID`,`EQUIPMENT_NAME`,`DESCRIPTION`,`CREATION_DATE`,`PRICE`,`TOTAL_QUANTITY`,`AVAILABLE_QUANTITY`,`OTHER_TEXT`) VALUES (88,1,"Bateau à moteur","ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor","2020-08-10",83,4,3,"Integer"),(2,5,"Bateau à moteur","magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien,","2020-07-30",107,9,4,"justo nec ante. Maecenas mi felis, adipiscing fringilla,"),(86,5,"Balle de tennis","felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non","2020-12-26",74,8,1,"purus mauris a nunc. In at pede. Cras vulputate velit"),(62,1,"Fillet de volley","ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam","2020-09-26",79,5,1,"volutpat. Nulla facilisis."),(25,1,"Ballon de basket","ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu","2020-08-10",44,4,3,"Nulla"),(97,3,"Table de ping-png","eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla","2020-09-08",77,7,4,"penatibus et magnis dis parturient montes, nascetur"),(100,1,"Surf","mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec,","2020-05-10",148,6,2,"vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo"),(86,4,"Ski nautique","arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc","2020-11-25",190,4,1,"lectus ante dictum mi, ac"),(52,3,"Fillet de volley","id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus","2021-01-12",52,7,3,"amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet"),(87,2,"Combinaison de ski","nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis","2020-07-12",114,5,1,"Fusce dolor quam, elementum at,");
INSERT INTO `EQUIPMENT` (`RENTER_ID`,`CATEGORY_ID`,`EQUIPMENT_NAME`,`DESCRIPTION`,`CREATION_DATE`,`PRICE`,`TOTAL_QUANTITY`,`AVAILABLE_QUANTITY`,`OTHER_TEXT`) VALUES (26,3,"Chaussures à crampons","velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer","2021-03-31",109,7,2,"vitae purus gravida sagittis. Duis gravida. Praesent eu"),(83,5,"Ferrari","sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus","2021-04-18",153,10,4,"tincidunt tempus risus."),(63,2,"Surf","Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna.","2020-09-20",25,9,2,"nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis"),(100,3,"Combinaison de ski","magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh","2021-03-11",98,7,4,"posuere cubilia Curae; Donec tincidunt. Donec vitae"),(69,3,"Bateau à voile","neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce","2021-01-09",31,7,1,"non leo. Vivamus nibh dolor, nonummy ac, feugiat non,"),(53,3,"Chaussures à crampons","cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus","2020-05-04",157,7,2,"dolor, nonummy ac,"),(35,3,"Combinaison de ski","nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit","2020-12-25",115,9,4,"sodales. Mauris blandit enim consequat purus. Maecenas"),(93,4,"Ballons de foot","vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris.","2021-04-25",129,5,1,"faucibus. Morbi vehicula."),(20,3,"Table de ping-png","magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna.","2020-06-14",191,8,4,"posuere, enim nisl elementum purus, accumsan interdum libero dui nec"),(67,2,"Panier de basket","id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim","2020-08-16",84,10,2,"risus. Donec");
INSERT INTO `EQUIPMENT` (`RENTER_ID`,`CATEGORY_ID`,`EQUIPMENT_NAME`,`DESCRIPTION`,`CREATION_DATE`,`PRICE`,`TOTAL_QUANTITY`,`AVAILABLE_QUANTITY`,`OTHER_TEXT`) VALUES (39,4,"Panier de basket","turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu","2020-09-19",163,10,1,"Ut tincidunt vehicula risus. Nulla eget metus eu erat semper"),(13,5,"Ballons de foot","interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc,","2020-11-20",60,4,2,"tristique pharetra. Quisque ac libero nec ligula"),(85,3,"Barque","Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices","2021-03-10",110,5,1,"vestibulum nec, euismod in, dolor."),(44,5,"Bateau à moteur","congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla","2020-07-12",64,6,4,"lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus"),(77,1,"Raquette de ping-pong","tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse","2021-02-10",62,5,3,"feugiat non, lobortis quis, pede. Suspendisse dui. Fusce"),(14,2,"Corde à sauter","ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam","2020-08-08",186,9,2,"elit. Etiam laoreet, libero et tristique"),(9,3,"Corde d'escalade","id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque","2020-11-20",155,5,2,"augue."),(97,1,"Balle de tennis","ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus.","2020-08-14",30,6,2,"Donec egestas. Duis ac arcu. Nunc mauris. Morbi"),(24,5,"Ski nautique","in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing","2020-05-11",83,10,2,"non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum"),(75,2,"Table de ping-png","enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc","2020-12-11",117,6,4,"at,");




